# -*- coding: utf-8 -*-
"""air travel safety.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YDuumE3j04hS0uvi40z-OhgMFocvDe0C
"""

#!/usr/bin/env python3
"""
FINAL AIRLINE SAFETY DASHBOARD - EXACT CELL REFERENCE LAYOUT (FIXED)
================================================================================
"""

import pandas as pd
import numpy as np
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.chart import BarChart, PieChart, Reference
from openpyxl.styles import Border, Side
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
import warnings
warnings.filterwarnings('ignore')



class DashboardConfig:
    COLORS = {
        'primary_blue': '1F4E79', 'success_green': '70AD47',
        'warning_orange': 'F79646', 'danger_red': 'C00000',
        'white': 'FFFFFF', 'dark_gray': '44546A'
    }
THIN_BLACK = Side(style='thin', color='000000')
THICK_BLACK = Side(style='thick', color='000000')

def apply_border_to_range(ws, start_cell, end_cell):
    """Apply thin black border to entire range"""
    thin_side = Side(style='thin', color='000000')
    thin_border = Border(
        left=thin_side,
        right=thin_side,
        top=thin_side,
        bottom=thin_side
    )
    for row in ws[start_cell + ':' + end_cell]:
        for cell in row:
            cell.border = thin_border


def load_and_process_data():
    df = pd.read_csv('airline-safety.csv')
    BILLION_ASK = 1_000_000_000
    df['ask_billions'] = df['avail_seat_km_per_week'] * 52 / BILLION_ASK
    df['fatal_rate_00_14'] = (df['fatalities_00_14'] * 15) / df['ask_billions']
    df['fatal_acc_rate_00_14'] = (df['fatal_accidents_00_14'] * 15) / df['ask_billions']
    df['safety_score'] = 100 * (
        0.6 * (1 - df['fatal_rate_00_14'] / df['fatal_rate_00_14'].max()) +
        0.4 * (1 - df['fatal_acc_rate_00_14'] / df['fatal_acc_rate_00_14'].max())
    )
    df['risk_level'] = pd.cut(df['safety_score'],
                              [0, 40, 65, 85, 100],
                              labels=['🔴 HIGH', '🟡 MEDIUM', '🟢 LOW', '✅ SAFE'])
    return df

def create_single_sheet_dashboard(df):
    wb = Workbook()
    ws = wb.active
    ws.title = "Airline Safety Dashboard"

    # =============================================================================
    # EXECUTIVE SUMMARY (A1:I17) - Top Left
    # =============================================================================
    # ✅ FIX: Set value BEFORE merge
    ws['A1'] = "✈️ AIRLINE SAFETY EXECUTIVE DASHBOARD 1985-2014"
    ws['A1'].font = Font(size=20, bold=True, color=DashboardConfig.COLORS['white'])
    ws['A1'].fill = PatternFill(start_color=DashboardConfig.COLORS['primary_blue'], fill_type='solid')
    ws['A1'].alignment = Alignment(horizontal='center', vertical='center')
    ws.merge_cells('A1:H3')  # AFTER setting value

    ws['A5'] = f"Analysis Date: February 11, 2026"
    ws['A5'].font = Font(size=12, italic=True, color='000000')
    ws.merge_cells('A5:B6')

    ws['A7'] = f"🎯 KEY SAFETY METRICS"
    ws['A7'].font = Font(size=12, bold=True, color='FFFFFF')
    ws['A7'].fill = PatternFill(start_color='76933C', fill_type='solid')
    ws.merge_cells('A7:B7')

    # Key Metrics (A7:B12)
    metrics = [
        ("Total Airlines", len(df)),
        ("Top Safety Score", f"{df['safety_score'].max():.0f}/100"),
        ("High Risk Airlines", len(df[df['risk_level']=='🔴 HIGH']))
    ]
    for i, (label, value) in enumerate(metrics):
        ws[f'A{i+8}'] = label
        ws[f'B{i+8}'] = value

    apply_border_to_range(ws,'A8','B10')

    # Top 5 header - FIXED
    ws['A11'] = "🏆 TOP 5 SAFEST AIRLINES"
    ws['A11'].font = Font(bold=True, size=12, color='FFFFFF')
    ws['A11'].fill = PatternFill(start_color='76933C', fill_type='solid')
    ws.merge_cells('A11:B11')

    top5 = df.nlargest(5, 'safety_score')[['airline', 'safety_score']].round(0)
    for i, (_, row) in enumerate(top5.iterrows()):
        ws[f'A{i+12}'] = row['airline'][:20]
        ws[f'B{i+12}'] = f"{row['safety_score']}/100"

    apply_border_to_range(ws,'A12','B16')

    # Green header styling for metrics
    for row in range(12,17):
        ws[f'A{row}'].font = Font(bold=True)
        ws[f'A{row}'].fill = PatternFill(start_color='EBF1DE', fill_type='solid')
        ws[f'B{row}'].font = Font(bold=True)
        ws[f'B{row}'].fill = PatternFill(start_color='EBF1DE', fill_type='solid')

    # =============================================================================
    # RISK HEATMAP (D5:I17) - Top Right
    # =============================================================================
    # ✅ FIX: Set value BEFORE merge
    ws['D5'] = "🔥 TOP 10 HIGHEST RISK AIRLINES"
    ws['D5'].font = Font(size=14, bold=True, color='FFFFFF')
    ws['D5'].fill = PatternFill(start_color=DashboardConfig.COLORS['danger_red'], fill_type='solid')
    ws['D5'].alignment = Alignment(horizontal='center')
    ws.merge_cells('D5:H6')

    headers = ['Rank', 'Airline', 'Score', 'Risk', 'Fatalities']
    for col, header in enumerate(headers, 4):  # D=4 to H=8
        cell = ws.cell(row=7, column=col, value=header)
        cell.font = Font(bold=True, color='FFFFFF', size=10)
        cell.fill = PatternFill(start_color=DashboardConfig.COLORS['dark_gray'], fill_type='solid')


    high_risk = df.nsmallest(8, 'safety_score')[['airline', 'safety_score', 'risk_level', 'fatalities_00_14']].round(0)
    for rank, (_, row) in enumerate(high_risk.iterrows(), 1):
        row_pos = 8 + rank
        ws.cell(row=row_pos, column=4, value=rank).font = Font(bold=True)
        ws.cell(row=row_pos, column=5, value=row['airline'][:15]).alignment = Alignment(wrap_text=True)
        score_cell = ws.cell(row=row_pos, column=6, value=f"{row['safety_score']:.0f}")

        if row['safety_score'] <40:
            score_cell.fill = PatternFill(start_color='C80000', fill_type='solid')
        if row['safety_score'] >40 and row['safety_score']<65:
            score_cell.fill = PatternFill(start_color='F46414', fill_type='solid')
        if row['safety_score'] >65 and row['safety_score']<85:
            score_cell.fill = PatternFill(start_color='F59F13', fill_type='solid')
        if row['safety_score'] >=85:
            score_cell.fill = PatternFill(start_color='F9E18B', fill_type='solid')
        ws.cell(row=row_pos, column=7, value=row['risk_level'])
        ws.cell(row=row_pos, column=8, value=int(row['fatalities_00_14']))
    apply_border_to_range(ws,'D8','H16')

    # =============================================================================
    # DASHBOARD TITLE (A19:I20)
    # =============================================================================
    ws['A19'] = "📊 INTERACTIVE SAFETY RANKINGS & CHARTS"
    ws['A19'].font = Font(size=16, bold=True, color='FFFFFF')
    ws['A19'].fill = PatternFill(start_color=DashboardConfig.COLORS['primary_blue'], fill_type='solid')
    ws['A19'].alignment = Alignment(horizontal='center')
    ws.merge_cells('A19:D20')

    # =============================================================================
    # 2x2 PERFECT GRID LAYOUT
    # =============================================================================
    # Top10 Safest (A22:D33)

    ws['A21'] = "🏆 TOP 10 SAFEST AIRLINES"
    ws['A21'].font = Font(bold=True, size=14, color='FFFFFF')
    ws['A21'].fill = PatternFill(start_color='366092', fill_type='solid')
    ws['A21'].alignment = Alignment(horizontal='center')
    ws.merge_cells('A21:D22')

    for col, header in enumerate(['Rank', 'Airline', 'Score', 'Risk'], 1):
        cell = ws.cell(row=23, column=col, value=header)
        cell.font = Font(bold=True, color='FFFFFF')
        cell.fill = PatternFill(start_color=DashboardConfig.COLORS['success_green'], fill_type='solid')

    top10_safe = df.nlargest(10, 'safety_score')[['airline', 'safety_score', 'risk_level']].round(0)
    for rank, (_, row) in enumerate(top10_safe.iterrows(), 1):
        row_pos = 23 + rank
        ws.cell(row=row_pos, column=1, value=row['airline'][:20])
        ws.cell(row=row_pos, column=2, value=rank).font = Font(bold=True)
        ws.cell(row=row_pos, column=3, value=f"{row['safety_score']:.0f}/100").font = Font(color=DashboardConfig.COLORS['success_green'], bold=True)
        ws.cell(row=row_pos, column=4, value=row['risk_level'])

    apply_border_to_range(ws,'A23','D33')

    # Safety Score Comparison (A35:B46)

    ws['A34'] = "📊 Safety Score Comparison"
    ws['A34'].font = Font(bold=True, size=14,color='FFFFFF')
    ws['A34'].fill = PatternFill(start_color='366092', fill_type='solid')
    ws['A34'].alignment = Alignment(horizontal='center')
    ws.merge_cells('A34:B35')

    for i, (_, row) in enumerate(top10_safe.iterrows()):
        row_pos = 36 + i
        ws.cell(row=row_pos, column=1, value=row['airline'][:18])
        ws.cell(row=row_pos, column=2, value=row['safety_score'])

    apply_border_to_range(ws,'A36','B45')

    # Risk Distribution (C35:D40) - FIXED with explicit ordering

    ws['C34'] = "📈 Risk Distribution"
    ws['C34'].font = Font(bold=True, size=14,color='FFFFFF')
    ws['C34'].fill = PatternFill(start_color='366092', fill_type='solid')
    ws['C34'].alignment = Alignment(horizontal='left')
    ws.merge_cells('C34:D35')

    risk_order = ['🔴 HIGH', '🟡 MEDIUM', '🟢 LOW', '✅ SAFE']
    risk_dist = df['risk_level'].value_counts().reindex(risk_order, fill_value=0)
    for i, (risk, count) in enumerate(risk_dist.items()):
        row_pos = 36 + i
        ws.cell(row=row_pos, column=3, value=str(risk))
        ws.cell(row=row_pos, column=4, value=count)
    apply_border_to_range(ws,'C35','D39')

    # COMBINED CHARTS (E22:I46)
    bar_chart = BarChart()
    bar_chart.type = "col"
    bar_chart.style = 10
    bar_chart.title = "Top 10 Safest"
    bar_chart.y_axis.title = "Safety Score"
    bar_chart.height = 7
    bar_chart.width = 12

    data_ref = Reference(ws, min_col=2, min_row=36, max_row=45, max_col=2)
    cats_ref = Reference(ws, min_col=1, min_row=36, max_row=45)
    bar_chart.add_data(data_ref, titles_from_data=False)
    bar_chart.set_categories(cats_ref)
    ws.add_chart(bar_chart, "E18")

    pie_chart = PieChart()
    pie_chart.title = "Risk Categories"
    pie_data = Reference(ws, min_col=4, min_row=36, max_row=39, max_col=4)
    pie_cats = Reference(ws, min_col=3, min_row=36, max_row=39)
    pie_chart.width= 12
    pie_chart.height=7
    pie_chart.add_data(pie_data)
    pie_chart.set_categories(pie_cats)
    ws.add_chart(pie_chart, "E32")

    # Perfect column widths
    column_widths = {'A':25.91, 'B':12.64, 'C':13, 'D':11, 'E':20.36, 'F':16.64, 'G':11.36, 'H':12, 'I':12}
    row_heights ={10:14.5,11:14.5,12:14.5}
    for col_letter, width in column_widths.items():
        ws.column_dimensions[col_letter].width = width
    for row_letter, height in row_heights.items():
        ws.row_dimensions[row_letter].height = height

    for row in ws.iter_rows():
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical='center')

     # 🆕 CENTER ALIGN EVERYTHING!
    center_alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
    for row in ws.iter_rows():
        for cell in row:
            cell.alignment = center_alignment

    output_file = 'Airline_Safety_Dashboard_EXACT.xlsx'
    wb.save(output_file)
    print(f"✅ EXACT LAYOUT MATCH: {output_file}")
    return output_file

if __name__ == "__main__":
    df = load_and_process_data()
    create_single_sheet_dashboard(df)